### ISSUE TITLE
Load last weight file with model.find_last()

### ISSUE THREAD

**Issue by mihiri91** [FlashTek/mask-rcnn-edge-agreement-loss#1]
Thank you very much for the useful implementation. 

When I try to load my last weight file with 

`!python3 top.py train --dataset=/content/drive/'My Drive'/Mask_RCNN/samples/top/dataset --weights=last`

It generated another log folder and gave me configuration errors.

I have notice that you added 
`
if self.config.RUN_NAME:
key += "_" + self.config.RUN_NAME
`
to `model.find_last()` different from [matterport](https://github.com/matterport/Mask_RCNN). May I ask you what is the purpose of it?

To fixed my error, I had to remove the newly added code and add `dir_name = os.path.join(self.model_dir, dir_names[-2])` as [here](https://github.com/matterport/Mask_RCNN/issues/885#issuecomment-419959504)

Detailed answers would be very helpful. 
Thank you in advance

**Comment by JulienSiems** [comment]
Hey @mihiri91, 

Is it possible that you tried to load from a model file from matterport Mask R-CNN with different naming? We changed the naming of our checkpoints during experimentation.

**Comment by mihiri91** [comment]
I'm sorry, can you explain little more? I'm confused with the word "naming".

**Comment by JulienSiems** [comment]
Happy to clarify, I meant the naming of the weights file from Matterport. Apart from the path error, are you otherwise able to train your models?

**Comment by mihiri91** [comment]
Thank you. yes, I am. I was able to train it with Matterport. Right now, I have also generated results as per your proposal.

**Comment by JulienSiems** [comment]
Great! Let us know if you have any more questions. Closing this issue for now.
